steps:
  
  ## account-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/account-service:prod','./account-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/account-service:prod' ]

  
  ## booking-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/booking-service:prod','./booking-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/booking-service:prod' ] 


  ## cinema-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/cinema-service:prod','./cinema-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/cinema-service:prod' ]
  
  ## gateway-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/gateway-service:prod','./gateway-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/gateway-service:prod' ]
  
  
  ## transaction-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/transaction-service:prod','./transaction-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/transaction-service:prod' ]
  
options:
  logging: CLOUD_LOGGING_ONLY