steps:
  
  ## account-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/account-service:prod','./account-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/account-service:prod' ]

  
  ## booking-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/booking-service:prod','./booking-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/booking-service:prod' ] 


  ## cinema-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/cinema-service:prod','./cinema-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/cinema-service:prod' ]
  
  ## gateway-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/gateway-service:prod','./gateway-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/gateway-service:prod' ]
  
  
  ## transaction-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/transaction-service:prod','./transaction-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/transaction-service:prod' ]


   ## frontend-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/frontend-service:prod','./frontend-service/']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/frontend-service:prod' ]
  
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gcloud deploy apply --file deploy/pipeline-sin-prod.yaml --region=asia-southeast1
        gcloud deploy apply --file deploy/sin-prod.yaml --region=asia-southeast1
        gcloud deploy releases create 'app-release-${SHORT_SHA}1' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/frontend-service.yaml
        gcloud deploy releases create 'app-release-${SHORT_SHA}2' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/gateway-service.yaml
        gcloud deploy releases create 'app-release-${SHORT_SHA}3' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/account-service.yaml
        gcloud deploy apply --file deploy/pipeline-in-prod.yaml --region=asia-southeast2
        gcloud deploy apply --file deploy/in-prod.yaml --region=asia-southeast2
        gcloud deploy releases create 'app-release-${SHORT_SHA}4' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/booking-service.yaml
        gcloud deploy releases create 'app-release-${SHORT_SHA}5' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/cinema-service.yaml
        gcloud deploy releases create 'app-release-${SHORT_SHA}6' --delivery-pipeline=mss301-cd --region=asia-southeast1 --from-k8s-manifest=./kubernetes/transaction-service.yaml
options:
  logging: CLOUD_LOGGING_ONLY