apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service-container
          image: asia-southeast1-docker.pkg.dev/mss301-462709/mss301-docker-artifact-registry/account-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
