apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service-container
          image: asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/account-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8084