apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-service
  template:
    metadata:
      labels:
        app: cinema-service
    spec:
      containers:
        - name: cinema-service-container
          image: asia-southeast1-docker.pkg.dev/just-metric-464414-c6/mss301-registry-artifact/cinema-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: cinema-service
spec:
  selector:
    app: cinema-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
